language: java

install:
  - npm install newman

before_script:
  - node --version
  - npm --version
  - node_modules/.bin/newman --version

script:
  - node_modules/.bin/newman run testes/client.postman_collection.json -e testes/teste.postman_environment.json
